import { Game } from '../types/value.type'

export const TEST_GAME: Game = [
  [
    { key: '1-1', value: '3', fixed: true },
    { key: '1-2', value: '' },
    { key: '1-3', value: '' },
    { key: '1-4', value: '4', fixed: true },
    { key: '1-5', value: '5', fixed: true },
    { key: '1-6', value: '' },
    { key: '1-7', value: '' },
    { key: '1-8', value: '' },
    { key: '1-9', value: '6', fixed: true },
  ],
  [
    { key: '2-1', value: '' },
    { key: '2-2', value: '' },
    { key: '2-3', value: '5', fixed: true },
    { key: '2-4', value: '' },
    { key: '2-5', value: '1', fixed: true },
    { key: '2-6', value: '6', fixed: true },
    { key: '2-7', value: '' },
    { key: '2-8', value: '' },
    { key: '2-9', value: '8', fixed: true },
  ],
  [
    { key: '3-1', value: '' },
    { key: '3-2', value: '' },
    { key: '3-3', value: '' },
    { key: '3-4', value: '' },
    { key: '3-5', value: '' },
    { key: '3-6', value: '' },
    { key: '3-7', value: '' },
    { key: '3-8', value: '7', fixed: true },
    { key: '3-9', value: '' },
  ],
  [
    { key: '4-1', value: '' },
    { key: '4-2', value: '' },
    { key: '4-3', value: '' },
    { key: '4-4', value: '' },
    { key: '4-5', value: '' },
    { key: '4-6', value: '1', fixed: true },
    { key: '4-7', value: '5', fixed: true },
    { key: '4-8', value: '4', fixed: true },
    { key: '4-9', value: '2', fixed: true },
  ],
  [
    { key: '5-1', value: '' },
    { key: '5-2', value: '' },
    { key: '5-3', value: '' },
    { key: '5-4', value: '6', fixed: true },
    { key: '5-5', value: '' },
    { key: '5-6', value: '2', fixed: true },
    { key: '5-7', value: '' },
    { key: '5-8', value: '' },
    { key: '5-9', value: '' },
  ],
  [
    { key: '6-1', value: '2', fixed: true },
    { key: '6-2', value: '9', fixed: true },
    { key: '6-3', value: '4', fixed: true },
    { key: '6-4', value: '8', fixed: true },
    { key: '6-5', value: '' },
    { key: '6-6', value: '' },
    { key: '6-7', value: '' },
    { key: '6-8', value: '' },
    { key: '6-9', value: '' },
  ],
  [
    { key: '7-1', value: '' },
    { key: '7-2', value: '7', fixed: true },
    { key: '7-3', value: '' },
    { key: '7-4', value: '' },
    { key: '7-5', value: '' },
    { key: '7-6', value: '' },
    { key: '7-7', value: '' },
    { key: '7-8', value: '' },
    { key: '7-9', value: '' },
  ],
  [
    { key: '8-1', value: '8', fixed: true },
    { key: '8-2', value: '' },
    { key: '8-3', value: '' },
    { key: '8-4', value: '3', fixed: true },
    { key: '8-5', value: '6', fixed: true },
    { key: '8-6', value: '' },
    { key: '8-7', value: '1', fixed: true },
    { key: '8-8', value: '' },
    { key: '8-9', value: '' },
  ],
  [
    { key: '9-1', value: '1', fixed: true },
    { key: '9-2', value: '' },
    { key: '9-3', value: '' },
    { key: '9-4', value: '' },
    { key: '9-5', value: '5', fixed: true },
    { key: '9-6', value: '2', fixed: true },
    { key: '9-7', value: '' },
    { key: '9-8', value: '' },
    { key: '9-9', value: '3', fixed: true },
  ],
]

export const EMPTY_GAME: Game = [
  [
    { key: '1-1', value: '' },
    { key: '1-2', value: '' },
    { key: '1-3', value: '' },
    { key: '1-4', value: '' },
    { key: '1-5', value: '' },
    { key: '1-6', value: '' },
    { key: '1-7', value: '' },
    { key: '1-8', value: '' },
    { key: '1-9', value: '' },
  ],
  [
    { key: '2-1', value: '' },
    { key: '2-2', value: '' },
    { key: '2-3', value: '' },
    { key: '2-4', value: '' },
    { key: '2-5', value: '' },
    { key: '2-6', value: '' },
    { key: '2-7', value: '' },
    { key: '2-8', value: '' },
    { key: '2-9', value: '' },
  ],
  [
    { key: '3-1', value: '' },
    { key: '3-2', value: '' },
    { key: '3-3', value: '' },
    { key: '3-4', value: '' },
    { key: '3-5', value: '' },
    { key: '3-6', value: '' },
    { key: '3-7', value: '' },
    { key: '3-8', value: '' },
    { key: '3-9', value: '' },
  ],
  [
    { key: '4-1', value: '' },
    { key: '4-2', value: '' },
    { key: '4-3', value: '' },
    { key: '4-4', value: '' },
    { key: '4-5', value: '' },
    { key: '4-6', value: '' },
    { key: '4-7', value: '' },
    { key: '4-8', value: '' },
    { key: '4-9', value: '' },
  ],
  [
    { key: '5-1', value: '' },
    { key: '5-2', value: '' },
    { key: '5-3', value: '' },
    { key: '5-4', value: '' },
    { key: '5-5', value: '' },
    { key: '5-6', value: '' },
    { key: '5-7', value: '' },
    { key: '5-8', value: '' },
    { key: '5-9', value: '' },
  ],
  [
    { key: '6-1', value: '' },
    { key: '6-2', value: '' },
    { key: '6-3', value: '' },
    { key: '6-4', value: '' },
    { key: '6-5', value: '' },
    { key: '6-6', value: '' },
    { key: '6-7', value: '' },
    { key: '6-8', value: '' },
    { key: '6-9', value: '' },
  ],
  [
    { key: '7-1', value: '' },
    { key: '7-2', value: '' },
    { key: '7-3', value: '' },
    { key: '7-4', value: '' },
    { key: '7-5', value: '' },
    { key: '7-6', value: '' },
    { key: '7-7', value: '' },
    { key: '7-8', value: '' },
    { key: '7-9', value: '' },
  ],
  [
    { key: '8-1', value: '' },
    { key: '8-2', value: '' },
    { key: '8-3', value: '' },
    { key: '8-4', value: '' },
    { key: '8-5', value: '' },
    { key: '8-6', value: '' },
    { key: '8-7', value: '' },
    { key: '8-8', value: '' },
    { key: '8-9', value: '' },
  ],
  [
    { key: '9-1', value: '' },
    { key: '9-2', value: '' },
    { key: '9-3', value: '' },
    { key: '9-4', value: '' },
    { key: '9-5', value: '' },
    { key: '9-6', value: '' },
    { key: '9-7', value: '' },
    { key: '9-8', value: '' },
    { key: '9-9', value: '' },
  ],
]
